#!/bin/sh
# Wrapper around apt-get to colorize its output
#
# Run with --short as the first argument to shorten each line so it fits
# on the screen

if [ "$TERM" = "dumb" ]; then
	exec apt-get "$@"
fi

# truncated output?
if [ "$1" = "--short" ]; then
	SIZE=$(stty size)
	shift
else
	SIZE=""
fi

/usr/bin/apt-cache $* 2>&1 | ~/colorapt/cache.pl $*
